### ISSUE TITLE
Update imports after changing theme name

### ISSUE THREAD

**Issue by BryceRussell** [astrolicious/astro-theme-provider#7]
Currently, if you update the name of the theme, all the imports inside the theme will become invalid. Astro Theme Provider could automatically update these imports across the package using something like [`ts-morph`](https://www.npmjs.com/package/ts-morph) or [`recast`](https://www.npmjs.com/package/recast) to read the imports inside the files and update them

**Things to consider**:
- How does `astro-theme-provider` know what the previous theme name was? 
- Can you use `ts-morph` or `recast` update imports inside `.astro` files? If not, what is an alternative?
- How does `astro-theme-provider` know if someone is _authoring/developing_ a theme or if someone is _using_ the theme? Ideally, this code would only run while authoring a theme to prevent unnecessary code execution while using a theme

**Comment by BryceRussell** [comment]
**Alternative idea**: Instead of updating a theme's files directly, migrate all themes to use an intermediate base import name like `from "theme/XXXX"` and all the naming/resolving for the import gets handled behind the scenes by a Vite plugin. This would solve the problem of renaming a theme breaking all the imports and makes themes more resilient to breaking changes.

**Comment by altsalt** [comment]
To address:
> - How does `astro-theme-provider` know what the previous theme name was?

As I explore ATP, it seems like there may be a point of having a directory of sidecar files. For instance, the example template has `title` and `description` added directly to `astro.config.mjs`, whereas child sites might have a `data/` directory with a variety of lists that are imported into the config. Bringing this back to the question at hand, themes might have a `data/` directory with files that define some of these variables.

**Comment by altsalt** [comment]
I see what you mean about this being a sort of Content Collection. Perhaps these all fall into the collection of `ConfigData` (often I've seen it referred to as `SiteData`). That said, I get the feeling that we'll want some way to filter the ones that mirror the same structure but will be injected into a different file than `astro.config.mjs`.

In terms of your current ideas, I know the hope is the playground is being run always, but can forsee this getting to an out-of-sync state. Regarding the second one, `/.astro` and `/node_modules` are not always checked-in to source control, unsure if that is a problem since the previous name is only relevant when first changed, but should be considered. And I've seen chatter elsewhere about `package.json` already being overloaded with options.

Definitely excited to spend some time actually implementing a new theme and chatting as I go, probably sometime over the next few days/week!

**Comment by BryceRussell** [comment]
This would be a cool feature to support, but not really necessary and would require some magic. I am going to close this for now so that I can clean up issues, maybe we can revisit in the future.
